# Generated by Django 5.2.8 on 2026-02-26 19:35

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=django.contrib.postgres.indexes.GinIndex(fields=['mother_name'], name='events_gin_mother_name', opclasses=['gin_trgm_ops']),
        ),
    ]
